const data = {
  Products: [
    {
      id: 1,
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "https://amazona.webacademy.pro/images/p1.jpg",
      price: 120,
      countInStock:10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      id: 2,
      name: "Aadidas Shirt",
      category: "Shirts",
      image: "https://amazona.webacademy.pro/images/p2.jpg",
      price: 220,
      countInStock:0,
      brand: "Aadidas",
      rating: 3.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      id: 3,
      name: "Lacoste Free Shirt",
      category: "Shirts",
      image: "https://amazona.webacademy.pro/images/p3.jpg",
      price: 420,
      countInStock:12,
      brand: "Lacoste",
      rating: 4.8,
      numReviews: 15,
      description: "high quality product",
    },
    {
      id: 4,
      name: "Nike Slim pants",
      category: "pants",
      image: "https://amazona.webacademy.pro/images/p4.jpg",
      price: 620,
      countInStock:17,
      brand: "Nike",
      rating: 4.7,
      numReviews: 12,
      description: "high quality product",
    },
    {
      id: 5,
      name: "puma Slim pants",
      category: "pants",
      image: "https://amazona.webacademy.pro/images/p5.jpg",
      price: 520,
      countInStock:17,
      brand: "Puma",
      rating: 2.5,
      numReviews: 11,
      description: "high quality product",
    },
    {
      id: 6,
      name: "Killers Slim pants",
      category: "pants",
      image: "https://amazona.webacademy.pro/images/p6.jpg",
      price: 620,
      countInStock:4,
      brand: "Killers",
      rating: 4.2,
      numReviews: 8,
      description: "high quality product",
    },
  ],
};

export default data;